name: Generate files.json
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate files.json
        run: |
          node -e "require('fs').writeFileSync('generate-files.js', `// generate-files.js
import { promises as fs } from 'fs';
import path from 'path';
const ROOT = process.cwd();
async function walk(dir, acc=[]) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) await walk(full, acc);
    else if (e.isFile() && e.name.toLowerCase().endsWith('.glb')) {
      const rel = path.relative(ROOT, full).split(path.sep).join('/');
      acc.push(rel);
    }
  }
  return acc;
}
const files = (await walk(ROOT, [])).sort((a,b)=> a.localeCompare(b));
await fs.writeFile('files.json', JSON.stringify(files, null, 2));
console.log(\`✓ files.json (${files.length})\`);
`)"
          node -e "require('fs').writeFileSync('package.json', `{"name": "panelmodels", "version": "1.0.0", "type": "module", "scripts": {"gen": "node generate-files.js"}}`)"
          node generate-files.js
      - name: Commit changes if any
        uses: EndBug/add-and-commit@v9
        with:
          add: 'files.json'
          message: 'chore: update files.json'
          default_author: github_actions
